# Generated by Django 5.2.7 on 2025-10-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_slug_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.PositiveIntegerField(default='123456'),
            preserve_default=False,
        ),
    ]
