# Generated by Django 5.2.7 on 2025-10-14 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_address_zip'),
    ]

    operations = [
        migrations.RunSQL(""""
            INSERT INTO store_collection (title)
            VALUES ('collection1')
        """)
    ]
